import React from 'react'

export default () => (
  <div className="container">
    <div className="row">
      <div className="col-xs-12">
        <h3>Terms & Conditions</h3>

        <p>These terms and conditions govern your use of the ElectricForge.us website and all products, features, applications, and services (collectively, "Service" or "Services") provided by Electric Forge, Inc. doing business as Electric Forge ("we", "us", "Electric Forge") to you (the "Subscriber", "you", or "your"), together with our Privacy Policy (collectively, the "Terms of Service" or "Agreement"). Please read the Terms of Service carefully before using the Services. These Terms of Service apply to all users of the Services, including without limitation any sub-users. Using the Services in any way constitutes acceptance of and agreement to be bound by the Terms of Service and any operating rules or procedures we establish and publish from time to time on our website, each of which is herein incorporated by reference and each of which may be updated at any time without notice to you. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, YOU MAY NOT USE THE SERVICES AND YOU SHOULD EXIT THE WEBSITE AND STOP USING THE SERVICES IMMEDIATELY.</p>

        <p>Electric Forge reserves the right to modify the Terms of Service at any time and without notice to you. Amendments and modifications shall take effect immediately upon publication on the Website or within a Service. By continuing to use Services after any such modifications, you agree to be bound by such amended or modified Terms of Service. For this reason, we encourage you to review the Terms of Service each time you use a Service. If you do not agree to any changes in the Terms of Service, you must immediately stop using the Services and Website. For the avoidance of doubt, no unilateral amendment will retroactively modify agreed dispute-resolution provisions of this Agreement, if any — including for example arbitration provisions — for then-pending disputes unless the parties expressly agree otherwise.</p>

        <p>Except as otherwise noted, all website contents are copyright &copy; 2018 Electric Forge, Inc. All rights reserved. Unauthorized use is prohibited.</p>

        <h4>Eligibility</h4>
        <p>The Products and Services (collectively Service or Services) are not targeted towards, nor intended for use by, anyone under the age of 13. By using the Services, you represent and warrant that you are 13 years of age or older. If you are under the age of 13, you may not, under any circumstances or for any reason, use the Services. We may, in our sole discretion, refuse to offer the Services to any person or entity and change its eligibility criteria at any time. You are solely responsible for ensuring that these Terms of Service are in compliance with all laws, rules and regulations applicable to you and the right to access the Services is revoked where these Terms of Service or use of the Services is prohibited or to the extent offering, sale or provision of the Services conflicts with any applicable law, rule or regulation. Further, the Services are offered only for your use, and not for the use or benefit of any third party.</p>

        <p>To sign up for the Services, you must register for an account on the Services (an “Account”). Only one Account may be created per person, unless Electric Forge grants permission otherwise in its sole discretion. You must provide accurate and complete information and keep your Account information updated. You shall not: (i) select or use as a username a name of another person with the intent to impersonate that person; (ii) use as a username a name subject to any rights of a person other than you without appropriate authorization; or (iii) use, as a username, a name that is otherwise offensive, vulgar or obscene. You are solely responsible for the activity that occurs on your Account, regardless of whether the activities are undertaken by you, your employees or a third party (including your contractors or agents), and for keeping your Account password secure. You may never use another person’s user account or registration information for the Services without permission. You must notify us immediately of any change in your eligibility to use the Services (including any changes to or revocation of any licenses from state authorities), breach of security or unauthorized use of your Account. You should never publish, distribute or post login information for your Account. You shall have the ability to delete your Account, either directly or through a request made to one of our employees or affiliates. Electric Forge will not be liable for any loss or damage as a result of your failure to provide us with accurate information or to keep your Account secure.</p>

        <h4>Content</h4>
        <p>For purposes of these Terms of Service, the term “Content” includes, without limitation, information, data, text, written posts and comments, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible on or through the Services. For the purposes of this Agreement, “Content” also includes all User Content (as defined below).</p>

        <p>All Content added, created, uploaded, submitted, distributed, or posted to the Services by users (collectively “User Content”), whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such User Content. You represent that all User Content provided by you is accurate, complete, up-to-date, and in compliance with all applicable laws, rules and regulations. You acknowledge that all Content, including User Content, accessed by you using the Services is at your own risk and you will be solely responsible for any damage or loss to you or any other party resulting therefrom. We do not guarantee that any Content you access on or through the Services is or will continue to be accurate.</p>

        <p>The Services may contain Content specifically provided by us, our partners or our users and such Content is protected by copyrights, trademarks, service marks, patents, trade secrets or other proprietary rights and laws. You shall abide by and maintain all copyright notices, information, and restrictions contained in any Content accessed through the Services.</p>

        <p>Subject to these Terms of Service, we grant each user of the Services a worldwide, non-exclusive, non-sublicensable and non-transferable license to use (i.e., to download and display locally) Content solely for purposes of using the Services. Use, reproduction, modification, distribution or storage of any Content for other than purposes of using the Services is expressly prohibited without prior written permission from us. You shall not sell, license, rent, or otherwise use or exploit any Content for commercial use or in any way that violates any third party right.</p>

        <p>By submitting any User Content to the Website, excluding privately transmitted User Content, you hereby do and shall grant us a worldwide, non-exclusive, perpetual, royalty-free, fully paid, sublicensable and transferable license to use, aggregate, reproduce, distribute, prepare derivative works of, display, perform, and otherwise fully exploit such User Content in connection with the Website, the Services and our (and our successors’ and assigns’) businesses, including without limitation for promoting and redistributing part or all of the Website or the Services (and derivative works thereof) in any media formats and through any media channels (including, without limitation, third party websites and feeds), and including after your termination of your Account or the Services. You also hereby do and shall grant each user of the Website and/or the Services a non-exclusive, perpetual license to access any of your User Content that is available to such user on the Website, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Content, including after your termination of your Account or the Services. By submitting any User Content to the Services other than on the Website, you hereby do and shall grant us a worldwide, non-exclusive, perpetual, royalty-free, fully paid, sublicensable and transferable license to use, aggregate, reproduce, distribute, prepare derivative works of, display, and perform such User Content solely for the purpose of providing the Services. For clarity, the foregoing licenses granted to us and our users does not affect your other ownership or license rights in your User Content, including the right to grant additional licenses to your User Content, unless otherwise agreed in writing. You represent and warrant that you have all rights to grant such licenses to us without infringement or violation of any third party rights, including without limitation, any privacy rights, publicity rights, copyrights, trademarks, contract rights, or any other intellectual property or proprietary rights.</p>

        <h4>Rules of Conduct</h4>
        <p>As a condition of use, you promise not to use the Services for any purpose that is prohibited by these Terms of Service. You are responsible for all of your activity in connection with the Services, including the actions of any sub-users associated with your account.</p>

        <p>You agree that you will not transmit, distribute, post, store, link, or otherwise traffic in Content, information, software, or materials on or through the Service that (i) is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another's privacy, tortious, offensive, profane, contains or depicts pornography that is unlawful, or is otherwise inappropriate as determined by us in our sole discretion, (ii) you know is false, misleading, untruthful or inaccurate, (iii) constitutes unauthorized or unsolicited advertising, (iv) impersonates any person or entity, including any of our employees or representatives, or (v) includes anyone’s identification documents or sensitive financial information.</p>

        <p>You shall not: (i) take any action that imposes or may impose (as determined by us in our sole discretion) an unreasonable or disproportionately large load on our (or our third party providers’) infrastructure; (ii) interfere or attempt to interfere with the proper working of the Services or any activities conducted on the Services; (iii) bypass, circumvent or attempt to bypass or circumvent any measures we may use to prevent or restrict access to the Services (or other accounts, computer systems or networks connected to the Services); (iv) run any form of auto-responder or “spam” on the Services; (v) use manual or automated software, devices, or other processes to “crawl” or “spider” any page of the Website; (vi) harvest or scrape any Content from the Services; (vii) use the Services for high risk activities including but not limited to the operation of nuclear facilities, air traffic control, life support systems, or any other use where the failure of service could lead to death, personal injury, or environmental damage; or (viii) otherwise take any action in violation of our guidelines and policies.</p>

        <p>You shall not (directly or indirectly): (i) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Services (including without limitation any application), except to the limited extent applicable laws specifically prohibit such restriction, (ii) modify, translate, or otherwise create derivative works of any part of the Services, or (iii) copy, rent, lease, distribute, or otherwise transfer any of the rights that you receive hereunder. You shall abide by all applicable local, state, national and international laws and regulations.
        We also reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce these Terms of Service, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect the rights, property or safety of us, our users and the public.</p>

        <p>Subscribers are limited to one Account per person, unless Electric Forge grants prior permission for multiple Accounts to a Subscriber. Subscribers are prohibited from registering multiple Accounts without first notifying Electric Forge of that intent and obtaining permission. Electric Forge shall determine the existence of multiple Accounts connected to a single person in its sole discretion, including but not limited to the use of the same billing details by multiple accounts. Electric Forge shall have the right to automatically flag all such multiple Accounts as fraudulent or abusive, and Electric Forge may, without notification to the Subscriber of such Account, suspend the service of such Account or any other Account used by such Subscriber. The use of referral codes or discounts by multiple Accounts controlled by the same person is not allowed. Electric Forge also reserves the right to terminate a Subscriber's Account if it is targeted by malicious activity from other parties.</p>

        <p>Each coupon code or other promotional discount may only be used once per person. Subscribers agree that they will not attempt to circumvent this restriction by any means, including but not limited to registering multiple accounts. Multiple use of discount or promotional codes by the same person under different accounts shall constitute a grave breach of this agreement.</p>

        <p>The enumeration of violations in this Section of these Terms of Service is not meant to be exclusive, and Electric Forge provides notice hereby that it has and will exercise its authority to take whatever action is necessary, in its sole discretion, to protect the Services, Subscribers, and third parties from acts that would be inimical to the purposes of this Section of these Terms of Service.</p>

        <h4>Use of Services</h4>
        <p>Use of Services, including Payments are covered in customer Master Service Agreements (MSAs)
        Electric Forge accepts major credit cards. Other forms of payment may be arranged by contacting Electric Forge at support@electricforge.us. Please note that any payment terms presented to you in the process of using or signing up for paid Services are deemed part of this Agreement.</p>

        <p>We use third-party payment processors (the “Payment Processors”) to bill you through a payment account linked to your Account on the Services (your “Billing Account”) for use of the paid Services. The processing of payments will be subject to the terms, conditions and privacy policies of the Payment Processors in addition to this Agreement. We are not responsible for error by the Payment Processors. By choosing to use paid Services, you agree to pay us, through the Payment Processors, all charges at the prices then in effect for any use of such paid Services in accordance with the applicable payment terms and you authorize us, through the Payment Processors, to charge your chosen payment provider (your “Payment Method”). You agree to make payment using that selected Payment Method. We reserve the right to correct any errors or mistakes that it makes even if it has already requested or received payment.</p>

        <h4>Termination and Access</h4>
        <p>Electric Forge reserves the right, in our sole discretion, to terminate your access to all or any part of the Services at any time, with or without notice, effective immediately, including but not limited to as a result of your violation of any of these Terms of Service or any law. Electric Forge may provide prior notice of the intent to terminate Services to you if such notice will not, in Electric Forge' discretion, run counter to the intents and purposes of these Terms of Service.</p>





      </div>
    </div>
  </div>
)
